version: "3"
services:
  app:
    container_name: app
    build: ./php
    command: "php-fpm"
    volumes:
      - ./:/var/www/app
  nginx:
    container_name: nginx
    image: nginx:alpine
    command: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/sites-available/:/etc/nginx/sites-available
      - ./:/var/www/app
    ports:
      - "8000:8000"
    depends_on:
      - app
    entrypoint: sh -c "nginx"
  hot:
    container_name: hot
    image: node:13.13.0
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app
    command: npm run docker
    ports:
      - "8080:8080"
    depends_on:
      - app
      - nginx
