service: linebot-maker

provider:
  name: aws
  region: ap-northeast-1
  runtime: provided
  deploymentBucket: sls-deps
  stage: ${opt:stage, 'stg'}

plugins:
  - ./vendor/bref/bref

package:
  exclude:
    - node_modules/**
    - public/storage
    - storage/**
    - tests/**
    - public/js/app.js.gz
    - public/js/vendor.js.gz
    - public/js/manifest.js.gz
    - .git/**

functions:
  website:
    handler: public/index.php
    timeout: 300 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-73-fpm}
    events:
      - http: "ANY /"
      - http: "ANY /{proxy+}"
#  artisan:
#    handler: artisan
#    timeout: 120 # in seconds
#    layers:
#      - ${bref:layer.php-73} # PHP
#      - ${bref:layer.console} # The "console" layer
